import Header from './components/header'
import './globals.css'
import type { Metadata } from 'next'
import StoreProvider from './store/authProvider'
import { getUserFromCookie } from '@/lib/cookies'
import UserStateSetter from './components/userStateSetter'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const userFromCookie = getUserFromCookie()
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <UserStateSetter initialUserState={userFromCookie}></UserStateSetter>
          <Header></Header>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
