import Header from './components/header'
import './globals.css'
import type { Metadata } from 'next'
import StoreProvider from './store/authProvider'
import { getUserFromCookie } from '@/lib/cookies'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body>
        <StoreProvider initialState={getUserFromCookie()}>
          <Header></Header>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
